travis:
  secure:
    BINSTAR_TOKEN: hHf+8dLzTgvsGS+SQS1fZxNo+XMHcrpS0egMCHAvOmE1MVAhmisTP6oVLkWrP3IKDgl81OBF8mPGIE23GaCeV4c1qlSWMu0VDL7dZ0Co7mYpPSWkhYY00Vqm+izqn+xLoktCwxzZf4OmFnS6SlDX82Muvbshlfkg7gX79JOU8ScCNschz8OidUWd+xG8JaOdOv0glenw+kj91XEONxUzgDOyoYb4jkZg6XAuB0JCgMWTL/52U8zGxSJQmToG6ZB8GnZwMZAsuIPsopWeNsFeXHk7AA1eQI2IeyCkliK/+RA8lrqup/e7k2I9HxjMet4pZLlaHnLhcmr4tJhSiBBfVgykfAfmL0Oo7Vjk0wmvRs/e1PTRFIgYUpQTTGUjLAjrUq/PY/QAj4OznfCxroDmz/C8gbqYmroe+Sghq89zE2+eEh+Cum/w/zoCPk9OixIo+CQZsLQIblUWfA8LwfrRY40V58kv0RgsJ/H6Sk3d9j7/RulRdm26wcyPCXdCzfVuRjxiJXyf3gPusMovw4e76UJfldAvDQaiOEzYXvYsc96A0TA0PcFLsKPs7Ufrhvxu6ndyrfa6RCRfZwfRxZN7nRvJiskWAS+Z9TKFAf2czkQE0bhHvxObTTO6N9LhLwleILU7UFVvJt9PMju2CwgzTavtyzjxpJtRfBHy/+m5Cp0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
